### ISSUE TITLE
[FEAT] Hold `Shift` to select multi days

### ISSUE THREAD

**Issue by Quorafind** [Canna71/obsidian-chronology#1]
Nice Job !

Nice to have a feature that hold `shift` to select more than 7 days, like now I am on the 18th, I hold `shift` to click the 7th, and I can see the files between 7th~18th.

**Comment by Canna71** [comment]
I guess so... it would complicate a bit the timeline since it will get crowded with more days. Even now I am avoiding selecting a whole month because I reckoned it would be too crowded. But I will experiment a bit!

**Comment by Quorafind** [comment]
Thanks for thinking about this. Nice job again, you just need to do what you want to do 😁. Btw the heatmap in the calendar is also good job.

**Comment by Canna71** [comment]
Done in 1.1.0; I hope you like it!
