### ISSUE TITLE
Feature: Make first day of week configurable

### ISSUE THREAD

**Issue by arent-groebner** [Canna71/obsidian-chronology#12]
The plugin assumes that the first day of a week is Sunday. But for many countries of the world it's the Monday, not the Sunday.

Please make the first day of the week configurable.

I actually don't know if there are other conventions besides Sunday and Monday. Maybe it's a good idea, to let the user freely decide which day of the week should be considered as first day of the week.

**Comment by gokceozan** [comment]
Yes, please!

**Comment by drkn** [comment]
+1

**Comment by emma673r** [comment]
I second this!

**Comment by arent-groebner** [comment]
I just had a look at Google Calendar. You can configure Saturday, Sunday, Monday as first day of week. As this topic was presumably deeply researched by Google, we can assume that these tree days will suffice.

<img width="464" alt="image" src="https://github.com/Canna71/obsidian-chronology/assets/20967986/55e54019-a32f-4229-84d0-7b485619a717">

**Comment by Canna71** [comment]
Ok guys, take a look at version 1.1.6
I wonder why this was needed anyway, since by default it would use the configured display language.
Maybe you are using a different display language than your own culture? (I know I do :-) )

**Comment by arent-groebner** [comment]
> Ok guys, take a look at version 1.1.6 I wonder why this was needed anyway, since by default it would use the configured display language. Maybe you are using a different display language than your own culture? (I know I do :-) )

Thanks for implementing this!

And yes, I use English as display language even when I'm from another country, simply to avoid horrible translations.
