### ISSUE TITLE
creation date is changed on sync, cant use chronology

### ISSUE THREAD

**Issue by octrivera** [Canna71/obsidian-chronology#19]
I just sync my notes into another machine, that changed the creation date to today, shows like all notes were created today

Would be great if it could read creation date from YAML, and add that info every time a note is created.
Thank you

**Comment by Canna71** [comment]
You are right, this is a big limitation, I will address it ASAP.

**Comment by IENORI** [comment]
Just encountered this issue today when I pulled my changes and was looking up chronology. The Obsidian forums also had some discussion on this and may be a good read: https://forum.obsidian.md/t/preserve-creation-dates-when-using-obsidian-sync/24818/9

**Comment by Canna71** [comment]
Please Check version 1.1.9

**Comment by evanyfyip** [comment]
Love the plugin, I can't seem to get this to work however. I am using templater to insert in the created date and last modified metadata, but it seems like chronology isn't able to parse it.

Heres an example of the bug:
![image](https://github.com/user-attachments/assets/b20b9164-ae80-48eb-9c71-81c15a80ed8a)

I set the creation date, however it is not appearing in that week
