### ISSUE TITLE
UI displayed wried

### ISSUE THREAD

**Issue by yoghurtdewdew** [Canna71/obsidian-chronology#22]
<img width="283" alt="image" src="https://github.com/Canna71/obsidian-chronology/assets/63794438/23d908a6-b6dd-4501-9323-1f1b71038bfe">

It will occur when I click on a week number, they would move backwards with a wried highlight bluk instead of just highlight a line as you showed in readme.md.

**Comment by bfoujols** [comment]
I have the same problem
Obsidian version 1.4.13
Version Chronology 1.1.7

**Comment by Canna71** [comment]
Please check latest version 1.1.8.
Cheers.
