### ISSUE TITLE
Blocking on UI thread

### ISSUE THREAD

**Issue by Osigmae** [Canna71/obsidian-chronology#23]
It seems like chronology is blocking the UI thread when updating itself, leading to stuttering when writing things. Correct me if I'm wrong, but I've traced it to the function 'getNotesForCalendarItem' which had a time of 137.9 ms to update which blocked input in obsidian. 

![image](https://github.com/Canna71/obsidian-chronology/assets/58618877/ddac6d48-fe6c-4b6e-8878-8f4030fb371d)

**Comment by Canna71** [comment]
How many notes do you have in your vault? 140ms don't seem to much honestly if you have a big vault.

**Comment by stoweboyd** [comment]
I have a large vault, and recently noticed that the editor seemed to be lagging while typing. I tried dive and conquer, and stumbled on a configuration that disabled chronology, and the lag went away.

**Comment by Canna71** [comment]
I see... I will analyze the issue and will probably apply some debouncing to the update in order not to apply the filtering at every change.

**Comment by Canna71** [comment]
In 1.1.10 I added the option to disable the "heat" indication from the cells. This causes computation for each day of the month and with big Vault could be slow. I also increased the timeout from a change to when the view is updated.
Could you try v 1.1.10 and maybe disable the Compute Heap option and see if this solves your issue?

**Comment by jerviscui** [comment]
I found the same problem, I turned on monitoring and found that chronology paused my obsidian for 6 seconds.

Is it possible that the chronology work is triggered every time a file is saved?

**Comment by jerviscui** [comment]
Now, disable Compute Heat options, it works fine!

**Comment by Canna71** [comment]
@jerviscui yes, it is triggered because every time a file is saved the modification date changes. Unfortunately computing the heatmap is quite slow since it isn't indexed yet.
I will work on that.
