### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by ryanjrman** [Canna71/obsidian-chronology#25]
I really love everything this plugin does except for one thing. The UI makes it unusable. No matter how I scale my UI it is off the side of the screen unless it is stretched all the way to the center of the monitor. It seems to be related to the theme I am using. For some reason it stretches it out. If there was a scaling parameter in the settings that would be fantastic.
![image](https://github.com/Canna71/obsidian-chronology/assets/71186324/a00c6753-59cc-41cb-b3c0-30f3a7ed86d3)
![image](https://github.com/Canna71/obsidian-chronology/assets/71186324/46dd749c-d6c0-4356-8388-82b46e19473c)

**Comment by Canna71** [comment]
Could you tell me which theme you are using?

**Comment by Canna71** [comment]
Please check latest version, if you still have issues please reopen

**Comment by ryanjrman** [comment]
> Could you tell me which theme you are using?

It does seem to be a theme issue. I am using a dark mode Spectrum theme. Still does not work unfortunately. Sorry for the late response.

**Comment by ryanjrman** [comment]
> > Could you tell me which theme you are using?
> 
> It does seem to be a theme issue. I am using a dark mode Spectrum theme. Still does not work unfortunately. Sorry for the late response.

Ayo it works wit the newest update nevermind. Thanks for fixing!
