### ISSUE TITLE
Feature Request: Make Page Preview (Hover Link) optional

### ISSUE THREAD

**Issue by arent-groebner** [Canna71/obsidian-chronology#26]
The Page Preview (Hover Link) feature was requested by a bunch of people, but for me it's contra productive.

I'm using the plugin in "Simple List Display" mode. When scrolling through the list, searching for a special item, the page preview pops up every time, hiding the list of notes I actually want to see. This is is really annoying. Furthermore, the popup makes no sense for me since my notes have a rather large header, generated by a template. So the popup shows the mostly irrelevant header, hiding the note list I want to see.

Since there are apparently two types of people, the ones who like the popup, and the ones who don't, this behavior should be ideally configurable.

**Comment by Canna71** [comment]
Maybe you could disable it in the "Page Preview" plugin settings? Just disabling the "Reading view" setting should be enough.

**Comment by arent-groebner** [comment]
"Reading view" is already disabled in "Page Preview". Maybe the plugin doesn't respect these settings?

**Comment by Canna71** [comment]
I will double check. The plugin is not directly implementing the page preview,  but is simply signaling to Obsidian that the user is hovering on a internal link,  so this settings should be applied. Maybe I am wrong and it's not the reading view mode,  I will need to check.

**Comment by arent-groebner** [comment]
Since the plugin is simply signaling to Obsidian, I checked the "Page Preview" settings again. The settings page is labeled as "Require % to trigger page preview on hover". It turned out that I misunderstood the page. You don't have to activate an item to ACTIVATE the preview, you have to activate an item to DEACTIVATE the preview. So everything is actually working. My fault.

**Comment by aalexee** [comment]
Thanks for finding a solution for this. I was also a little concerned about this change in the default behavior.
