### ISSUE TITLE
QoL tweak

### ISSUE THREAD

**Issue by menagerie198** [Canna71/obsidian-chronology#3]
Could we have this little 'quality of life' styling tweak please - the ability to have the memo render in the Daily as a flat line, ie no bullet?
Also the ability to have more flexibility in the styling of that memo render. Specifically, what I would like is
```
## {TIME}
{{CONTENT}
```
in the 'Experimental>Default Memo Composition' section of 'Settings'. Not important - but would be nice :-)

**Comment by Canna71** [comment]
Sorry, I am not sure I fully understand, could you provide some example? I don't understand what you mean by bullet point and also Experimental>Default Memo Composition.
Thank you

**Comment by menagerie198** [comment]
Oh dear! I appear to have posted this request in entirely the wrong place. I am so sorry to waste your time. Classic PEBKAC.

**Comment by Canna71** [comment]
:-) no problem
