### ISSUE TITLE
The date is gone?

### ISSUE THREAD

**Issue by KDDG** [Canna71/obsidian-chronology#44]
Excuse me, but if there is anyone who meets the same question? The date is gone as shown in the picture.
![1](https://github.com/user-attachments/assets/91590c3c-edec-4d90-a991-a780b62ed73a)

**Comment by Citatap** [comment]
I'm suddenly experiencing the same problem as above.

**Comment by CassiesCurse** [comment]
Me too.

Each month in 2024 has just a single row with the days of the week listed underneath. I triple checked my settings and nothing has changed. Each month has a plain list of all documents underneath it, and most importantly, all "heat" data is gone.

This is how I see current months which contain data (same as above, but not in the future - if it makes a difference).

![IMG_20241229_135532](https://github.com/user-attachments/assets/44d5f430-8248-48cc-a0cb-84a4ad153eec)

**Comment by lyonsquark** [comment]
Yep - I'm seeing the same thing with 1.1.11 (latest)

**Comment by froses** [comment]
I have the same problem (Obsidian 1.8.0).

**Comment by jiangnanrusheng** [comment]
same as me
what happen,i didn't do anything

**Comment by Canna71** [comment]
Very sorry guys, it should have been fixed in 1.1.12.

**Comment by lyonsquark** [comment]
Thanks very much for fixing it! Happy New Year!
