### ISSUE TITLE
Off by 1 error when viewing dates in 2022

### ISSUE THREAD

**Issue by joshkpeterson** [Canna71/obsidian-chronology#6]
First just want to say, really exciting plugin! Just been using obsidian for a few months and when I found this plugin today, it made me appreciate obsidian all over again. Seems like some really core functionality, to be able to see a history of the notes you've edited.

I'm seeing a bug when I try to click on any date/week in 2022. When I click on eg December 31 2022,  all the dates vanish from the calendar, no notes are in the list, and now it reads December 202**3** up top. Similar things happen when I click on the week (sometimes the whole week is highlighted another color too).

Figured you would probably notice this soon yourself anyway if this is the first time we've crossed the year boundary since you wrote the plugin, but thought I might as well make a report. Thanks for your help.

**Comment by Xieleilab** [comment]
the same problem encountered!

**Comment by jerviscui** [comment]
the same problem encountered!

**Comment by TemperoTengu** [comment]
The same problem encountered.

**Comment by Canna71** [comment]
Thank you for reporting this, I will work on this.
As per the "month" view, at the moment that is a simple list of notes, I will try to improve with some sort of time line in the future.

**Comment by Canna71** [comment]
It was a big oversight on my side: some calculations were done for the current year, and not the one displayed.
Sorry folks, should be fixed in 1.1.1
