### ISSUE TITLE
when the language of obsidian is not in english(e.g., chinese), the panel for january 2023 can not be displayed normally

### ISSUE THREAD

**Issue by Xieleilab** [Canna71/obsidian-chronology#8]
when the language of obsidian is not in english(e.g., chinese), the panel for january 2023 can not be displayed normally
![image](https://user-images.githubusercontent.com/78771561/211010924-81a311dd-b309-41c0-bc14-fb77b1638e80.png)

**Comment by Canna71** [comment]
Have you tried with version 1.1.1? There was ab issue (#6 ) that could cause this.

**Comment by Canna71** [comment]
I meant version 1.1.1 of the plugin. I released it today.

**Comment by Xieleilab** [comment]
yes,the version 1.1.1 still has the problem mentioned above

**Comment by Canna71** [comment]
I have found another issue in culture when the week starts with "monday", can you please update to 1.1.2?

**Comment by Canna71** [comment]
Please check also with 1.1.3
